# DO NOT EDIT, this is a generated file.

{
  imports = [
    ./core/admin/nix.nix
    ./core/console/git.nix
    ./core/console/packages.nix
    ./core/console/pandoc.nix
    ./core/console/zsh.nix
    ./core/graphic/education.nix
    ./core/graphic/gnome.nix
    ./core/graphic/imagery.nix
    ./core/graphic/music.nix
    ./core/graphic/obsidian.nix
    ./core/graphic/office.nix
    ./core/graphic/video.nix
    ./core/graphic/virt-manager.nix
    ./core/graphic/virtualbox.nix
    ./core/service/adguardhome.nix
    ./core/service/audio.nix
    ./core/service/dnsmasq.nix
    ./core/service/forgejo.nix
    ./core/service/home-assistant.nix
    ./core/service/homepage.nix
    ./core/service/httpd.nix
    ./core/service/immich.nix
    ./core/service/lldap.nix
    ./core/service/ncps.nix
    ./core/service/nextcloud.nix
    ./core/service/printing.nix
    ./core/system/core.nix
    ./core/system/documentation.nix
    ./core/system/hardware.nix
    ./core/system/i18n.nix
    ./core/system/sops.nix
    ./core/user/build.nix
    ./macro/host/desktop.nix
    ./macro/host/gateway.nix
    ./macro/host/laptop.nix
    ./macro/host/minimal.nix
    ./macro/host/portable.nix
    ./macro/host/server.nix
    ./macro/host/start-img.nix
    ./macro/host/vm.nix
    ./macro/theme/advanced.nix
    ./macro/theme/children.nix
    ./macro/theme/office.nix
    ./macro/theme/teenager.nix
  ];
}
