# DO NOT EDIT, this is a generated file.

{
  imports = [
    ./mixin/host/desktop.nix
    ./mixin/host/gateway.nix
    ./mixin/host/hcs.nix
    ./mixin/host/laptop.nix
    ./mixin/host/minimal.nix
    ./mixin/host/portable.nix
    ./mixin/host/server.nix
    ./mixin/host/vm.nix
    ./mixin/profile/advanced.nix
    ./standard/admin/nix.nix
    ./standard/console/git.nix
    ./standard/console/pandoc.nix
    ./standard/console/zsh.nix
    ./standard/graphic/gnome.nix
    ./standard/graphic/supertuxkart.nix
    ./standard/graphic/virt-manager.nix
    ./standard/graphic/virtualbox.nix
    ./standard/service/adguardhome.nix
    ./standard/service/audio.nix
    ./standard/service/dnsmasq.nix
    ./standard/service/element.nix
    ./standard/service/fail2ban.nix
    ./standard/service/forgejo.nix
    ./standard/service/headscale.nix
    ./standard/service/home-assistant.nix
    ./standard/service/homepage.nix
    ./standard/service/idm.nix
    ./standard/service/immich.nix
    ./standard/service/jellyfin.nix
    ./standard/service/jitsi-meet.nix
    ./standard/service/matrix.nix
    ./standard/service/mealie.nix
    ./standard/service/monitoring.nix
    ./standard/service/ncps.nix
    ./standard/service/nextcloud.nix
    ./standard/service/nfs.nix
    ./standard/service/outline.nix
    ./standard/service/postfix.nix
    ./standard/service/printing.nix
    ./standard/service/restic.nix
    ./standard/service/searx.nix
    ./standard/service/tailscale.nix
    ./standard/service/turn.nix
    ./standard/service/vaultwarden.nix
    ./standard/system/core.nix
    ./standard/system/documentation.nix
    ./standard/system/hardware.nix
    ./standard/system/i18n.nix
    ./standard/system/services.nix
    ./standard/system/sops.nix
    ./standard/system/srv-dirs.nix
    ./standard/user/build.nix
    ./standard/user/root.nix
  ];
}
