# DO NOT EDIT, this is a generated file.

{
  imports = [
    ./admin/nix.nix
    ./console/git.nix
    ./console/pandoc.nix
    ./console/zsh.nix
    ./graphic/gnome.nix
    ./graphic/supertuxkart.nix
    ./graphic/virt-manager.nix
    ./graphic/virtualbox.nix
    ./mixin/host/desktop.nix
    ./mixin/host/gateway.nix
    ./mixin/host/hcs.nix
    ./mixin/host/laptop.nix
    ./mixin/host/minimal.nix
    ./mixin/host/portable.nix
    ./mixin/host/server.nix
    ./mixin/host/vm.nix
    ./mixin/profile/advanced.nix
    ./security/complement.nix
    ./security/filesystem.nix
    ./security/integrity.nix
    ./security/journaling.nix
    ./security/kernel-build.nix
    ./security/kernel-params.nix
    ./security/mac.nix
    ./security/mta.nix
    ./security/network.nix
    ./security/nss.nix
    ./security/packages.nix
    ./security/pam.nix
    ./security/preboot.nix
    ./security/services.nix
    ./security/sudo.nix
    ./security/users.nix
    ./service/adguardhome.nix
    ./service/ai.nix
    ./service/audio.nix
    ./service/dnsmasq.nix
    ./service/docs.nix
    ./service/element.nix
    ./service/fail2ban.nix
    ./service/forgejo.nix
    ./service/garage.nix
    ./service/headscale.nix
    ./service/home-assistant.nix
    ./service/homepage.nix
    ./service/idm.nix
    ./service/immich.nix
    ./service/jellyfin.nix
    ./service/jitsi-meet.nix
    ./service/loki.nix
    ./service/matrix.nix
    ./service/mealie.nix
    ./service/minio.nix
    ./service/monitoring.nix
    ./service/ncps.nix
    ./service/nextcloud.nix
    ./service/nfs.nix
    ./service/outline.nix
    ./service/postfix.nix
    ./service/printing.nix
    ./service/restic.nix
    ./service/searx.nix
    ./service/tailscale.nix
    ./service/turn.nix
    ./service/vaultwarden.nix
    ./system/core.nix
    ./system/documentation.nix
    ./system/hardware.nix
    ./system/i18n.nix
    ./system/security.nix
    ./system/services.nix
    ./system/sops.nix
    ./system/srv-dirs.nix
    ./user/build.nix
    ./user/root.nix
  ];
}
