# Unified Multimodal Input (UMI)
#
# Touchscreen + voice + gaze (Talon autostart + Onboard).
#
# :::note[Session depends on the host]
# - **`darkone.host.umi` host**: Cinnamon X11 session (udev, uinput, Talon
#   provided by the host). Talon and a docked Onboard keyboard (word
#   prediction, sticky modifiers) start with the session. Panel, icons and
#   text enlarged for gaze targets (`panelHeight`, `textScaling`).
# - **Any other host**: GNOME Wayland with its native accessibility: on-screen
#   keyboard, big pointer and text. Talon and Onboard, X11-only, stay off.
#
# Dwell click: opt-in (`enableDwell`) under GNOME. In Cinnamon, a Talon user
# script makes it follow the eye tracker, with gaze control (`enableTrackerAuto`).
# :::
#
# :::tip[Community scripts]
# Set `communityScripts` to a fetched github:talonhub/community tree to get
# full voice and gaze mouse control (zoom mouse, pop click) declaratively.
# :::
#
# :::note[Dual schemas]
# Settings go to both families: org/cinnamon/* for the UMI host session,
# org/gnome/* for GNOME sessions elsewhere (mousetweaks reads it too).
# Exception: keys locked by the DNF gnome module are never written here,
# a write to a locked key aborts the whole home-manager `dconf load`.
# Screen locking stays enabled GNOME-side (locked by the DNF gnome module);
# `idle-delay = 0` avoids triggering it, and the Cinnamon session has its
# own lock fully disabled.
# :::
#
# :::caution[Login keyring: autologin user only, two modes decided by the host]
# An autologin session types no password, so PAM has nothing to hand to
# gnome-keyring and every secret-using app pops a gcr prompt the UMI user
# cannot answer. A password login unlocks the keyring as usual and is left
# alone. For the autologin user, the fix depends on the host:
#
# - **Unencrypted host**: the login keyring is seeded with an empty password,
#   which gnome-keyring stores in plain text and unlocks on its own (it tries
#   an empty password before prompting). Any pre-existing password-protected
#   keyring is deleted — its passphrase is untypable here, so it can only
#   produce the prompt forever. Autologin already grants the whole session to
#   whoever boots the machine, so this costs no real confidentiality.
# - **Encrypted host** (`darkone.system.luks.volumes` non-empty): nothing is
#   seeded. The passphrase typed at boot is cached in the kernel keyring and
#   handed to gnome-keyring by `pam_gdm`, so the keyring stays encrypted with
#   it. This is the only mode that protects the secrets at rest.
#
# Gotcha, encrypted hosts only: rotating the LUKS passphrase (sops value
# changed, `luks-passphrase-sync`) leaves the keyring on the old one — GNOME
# then reports "The password you use to log in to your computer no longer
# matches that of your login keyring". Delete
# `~/.local/share/keyrings/login.keyring` and log in again.
# :::
{
  lib,
  config,
  pkgs,
  osConfig,
  ...
}:
let
  cfg = config.darkone.home.umi;

  # Dwell click parameters shared by the GNOME and Cinnamon a11y schemas. The
  # toggles are written even when disabled: leaving the keys out would keep a
  # previously enabled dwell click alive in the user's dconf database.
  dwellSettings = {
    dwell-click-enabled = cfg.enableDwell;
    dwell-time = cfg.dwellTime;
    dwell-threshold = 15;
    secondary-click-enabled = cfg.enableDwell;
  };

  # Talon owns Cinnamon's toggle at runtime (tracker automation): writing it
  # here would switch hover click off at every activation.
  cinnamonDwellSettings = removeAttrs dwellSettings (
    lib.optional cfg.enableTrackerAuto "dwell-click-enabled"
  );

  # Talon user script: the tracker drives gaze control and hover click
  trackerScript = ''
    # DNF UMI (generated by home-manager): eye tracker plugged in -> gaze mouse
    # control and Cinnamon hover click on; unplugged -> hover click off.
    import subprocess

    from talon import actions, app, cron, usb
    from talon.track import tobii

    DCONF = "${pkgs.dconf}/bin/dconf"
    DWELL_KEY = "/org/cinnamon/desktop/a11y/mouse/dwell-click-enabled"


    def set_gaze(present: bool) -> None:

        # Stays requested without tracker: Talon's eye mouse starts on attach
        actions.tracking.control_toggle(True)
        subprocess.run([DCONF, "write", DWELL_KEY, "true" if present else "false"], check=False)


    def on_attach(dev) -> None:

        # Talon's own attach handler sets the tracker up first
        if isinstance(dev, tobii.TobiiEC):
            cron.after("1s", lambda: set_gaze(True))


    def on_detach(dev) -> None:
        if isinstance(dev, tobii.TobiiEC):
            set_gaze(False)


    app.register("ready", lambda: set_gaze(any(isinstance(d, tobii.TobiiEC) for d in usb.devices())))
    usb.register("attach", on_attach)
    usb.register("detach", on_detach)
  '';

  # Big cursor and text for gaze precision (~15-30 px)
  interfaceSettings = {
    cursor-size = 48;
    text-scaling-factor = 1.25;
  };

  # Cinnamon caps panel symbolic icons at 50 px
  symbolicIconSize = lib.min 50 (cfg.panelHeight * 5 / 8);

  # Applet settings forced at activation, by uuid and instance id. Values must
  # sit strictly inside the schema bounds: Cinnamon resets the others when it
  # completes a partial file.
  spicesSettings = [
    {
      uuid = "menu@cinnamon.org";
      id = 0;
      values = {
        category-icon-size = 32;
        application-icon-size = 40;
        sidebar-icon-size = 32;
      };
    }
  ];

  # gnome-keyring's on-disk format for a keyring with no password: plain ini
  # instead of the encrypted blob, unlocked at startup without a prompt.
  plainLoginKeyring = pkgs.writeText "login.keyring" ''
    [keyring]
    display-name=login
    ctime=0
    mtime=0
    lock-on-idle=false
    lock-after=false
  '';
  defaultKeyringName = pkgs.writeText "default-keyring" "login";

  # An encrypted host feeds the boot passphrase to gnome-keyring through
  # pam_gdm; seeding a passwordless keyring there would throw that away.
  hostHasLuks = (osConfig.darkone.system.luks.volumes or [ ]) != [ ];

  # A password login hands its password to gnome-keyring: seeding there would
  # swap an encrypted keyring for a plain one (UMI user on a non-UMI host).
  autoLogin = osConfig.services.displayManager.autoLogin;
  isAutoLoginUser = autoLogin.enable && autoLogin.user == config.home.username;
in
{
  options = {
    darkone.home.umi = {
      enable = lib.mkEnableOption "UMI multimodal input configuration (Talon + Onboard)";
      enableTalonAutostart = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Start Talon on session login (talon must be in PATH).";
      };
      communityScripts = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = null;
        description = "talonhub/community tree deployed to ~/.talon/user/community.";
      };
      enableDwell = lib.mkEnableOption ''
        dwell click: clicking by resting the pointer. Off by default — it is
        only usable with an eye tracker, and with a mouse it fires on whatever
        the pointer was left over (the a11y menu toggling zoom or the on-screen
        keyboard, typically)
      '';
      dwellTime = lib.mkOption {
        type = lib.types.float;
        default = 1.2;
        description = "Dwell click delay in seconds.";
      };
      enableTrackerAuto = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Eye tracker plugged in: Talon gaze mouse control and hover click on;
          unplugged: hover click off (Cinnamon session). Takes over
          `enableDwell` in Cinnamon.
        '';
      };
      panelHeight = lib.mkOption {
        type = lib.types.ints.between 40 96;
        default = 64;
        description = "Cinnamon panel height in pixels, its icons follow (gaze targets).";
      };
      textScaling = lib.mkOption {
        type = lib.types.float;
        default = 1.5;
        description = "Text scaling factor of the Cinnamon session (buttons grow with their labels).";
      };
    };
  };

  config = lib.mkIf cfg.enable {

    # Declarative Talon user scripts
    home.file.".talon/user/community" = lib.mkIf (cfg.communityScripts != null) {
      source = cfg.communityScripts;
      recursive = true;
    };
    home.file.".talon/user/dnf-umi/tracker.py" = lib.mkIf cfg.enableTrackerAuto {
      text = trackerScript;
    };

    # Cinnamon-only autostart, both installed by the UMI host: X11 clients,
    # useless under GNOME Wayland (Talon does not run, Onboard's XTest keys
    # never reach Wayland windows).
    xdg.configFile."autostart/talon.desktop" = lib.mkIf cfg.enableTalonAutostart {
      text = ''
        [Desktop Entry]
        Type=Application
        Name=Talon
        Exec=talon
        OnlyShowIn=X-Cinnamon;
        X-GNOME-Autostart-enabled=true
      '';
    };
    xdg.configFile."autostart/onboard.desktop".text = ''
      [Desktop Entry]
      Type=Application
      Name=Onboard
      Exec=onboard
      OnlyShowIn=X-Cinnamon;
      X-GNOME-Autostart-enabled=true
    '';

    dconf.settings = {

      # Dwell click (both schema families, cf. header)
      "org/cinnamon/desktop/a11y/mouse" = cinnamonDwellSettings;
      "org/gnome/desktop/a11y/mouse" = dwellSettings;
      "org/cinnamon/desktop/interface" = interfaceSettings // {
        text-scaling-factor = cfg.textScaling;
      };
      "org/gnome/desktop/interface" = interfaceSettings;

      # Taller panel, icons fit to it (0 = best fit for color icons)
      "org/cinnamon" = {
        panels-height = [ "1:${toString cfg.panelHeight}" ];
        panel-zone-icon-sizes = builtins.toJSON [
          {
            panelId = 1;
            left = 0;
            center = 0;
            right = 0;
          }
        ];
        panel-zone-symbolic-icon-sizes = builtins.toJSON [
          {
            panelId = 1;
            left = symbolicIconSize;
            center = symbolicIconSize;
            right = symbolicIconSize;
          }
        ];
      };

      # Nemo: big icons, single click opens (a dwell double click needs a mode
      # switch first)
      "org/nemo/preferences".click-policy = "single";
      "org/nemo/icon-view".default-zoom-level = "large";
      "org/nemo/list-view".default-zoom-level = "large";
      "org/gnome/desktop/a11y" = {
        always-show-universal-access-status = true;
      };

      # GNOME Shell's native keyboard stands in for Onboard. Cinnamon reads
      # `org/cinnamon/desktop/a11y/applications`: no double keyboard there.
      "org/gnome/desktop/a11y/applications".screen-keyboard-enabled = true;

      # A lock screen is a dead-end without a keyboard: disable Cinnamon
      # locking entirely and never let the session go idle. The GNOME
      # `lock-enabled` key is locked host-wide by the DNF gnome module, so
      # only `idle-delay = 0` (user-overridable) protects a GNOME session.
      "org/cinnamon/desktop/screensaver" = {
        lock-enabled = false;
        idle-activation-enabled = false;
      };
      "org/cinnamon/desktop/session".idle-delay = lib.hm.gvariant.mkUint32 0;
      "org/gnome/desktop/session".idle-delay = lib.hm.gvariant.mkUint32 0;

      # Onboard tuned for touch and gaze input: fixed docked position, big
      # high-contrast targets, sticky modifiers (no key holding), word
      # prediction to cut keystrokes, jitter tolerance.
      "org/onboard" = {
        layout = "Full Keyboard";
        theme = "HighContrast";
        use-system-defaults = false;
      };
      "org/onboard/window" = {
        docking-enabled = true;
        docking-edge = "bottom";
        force-to-top = true;
        window-decoration = false;
        transparency = 0.0;
      };
      "org/onboard/auto-show".enabled = false;
      "org/onboard/keyboard" = {
        long-press-delay = 2.0;
        touch-feedback-enabled = true;
        audio-feedback-enabled = true;
      };
      "org/onboard/typing-assistance".auto-capitalization = true;
      "org/onboard/typing-assistance/word-suggestions" = {
        enabled = true;
        delayed-word-separators-enabled = true;
        spelling-suggestions-enabled = true;
      };
      "org/onboard/universal-access" = {
        hide-click-type-window = false;
        enable-click-type-window-on-exit = true;
        drag-threshold = 20;
      };
    };

    # Cinnamon panels a UMI user cannot act on, hidden by a `NoDisplay` copy in
    # XDG_DATA_HOME: the cinnamon wrapper prepends its own `share/` to
    # XDG_DATA_DIRS, shadowing any `xdg.desktopEntries` override.
    home.file.".local/share/applications/cinnamon-settings-actions.desktop".text = ''
      [Desktop Entry]
      Type=Application
      Name=Actions
      Exec=cinnamon-settings actions
      NoDisplay=true
    '';
    home.file.".local/share/applications/cinnamon-settings-extensions.desktop".text = ''
      [Desktop Entry]
      Type=Application
      Name=Extensions
      Exec=cinnamon-settings extensions
      NoDisplay=true
    '';

    # Cinnamon's stock panel pins name `firefox.desktop`, DNF ships Firefox ESR
    # as `firefox-esr.desktop`: the pin resolves to nothing and the launcher is
    # silently dropped, leaving only Files and Terminal. Rewrite the id in
    # place rather than forcing the whole list, so pins added later survive.
    # The file only exists once Cinnamon has run: on a fresh home the fix
    # lands on the activation that follows the first login.
    home.activation.umiPanelLaunchers = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      for cfgFile in "$HOME"/.config/cinnamon/spices/grouped-window-list@cinnamon.org/*.json ; do
        [ -e "$cfgFile" ] || continue
        ${pkgs.jq}/bin/jq '."pinned-apps".value |= map(
          if . == "firefox.desktop" then "firefox-esr.desktop" else . end
        )' "$cfgFile" > "$cfgFile.new" || continue
        run ${pkgs.coreutils}/bin/mv -f "$cfgFile.new" "$cfgFile"
      done
    '';

    # Forced key by key: other values survive. A missing file gets the forced
    # keys only, Cinnamon completes it from the applet schema on next start
    # (no file monitor: changes apply at the next login).
    home.activation.umiCinnamonSpices = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      spicesSet() {
        cfgDir="$HOME/.config/cinnamon/spices/$1"
        cfgFile="$cfgDir/$2.json"
        run ${pkgs.coreutils}/bin/mkdir -p "$cfgDir"
        if [ -e "$cfgFile" ] ; then
          ${pkgs.jq}/bin/jq --argjson v "$3" \
            'reduce ($v | to_entries[]) as $e (.; .[$e.key].value = $e.value)' \
            "$cfgFile" > "$cfgFile.new" || return 0
        else
          ${pkgs.jq}/bin/jq -n --argjson v "$3" '$v | map_values({ value: . })' \
            > "$cfgFile.new" || return 0
        fi
        run ${pkgs.coreutils}/bin/mv -f "$cfgFile.new" "$cfgFile"
      }
      ${lib.concatMapStrings (
        s: "spicesSet ${s.uuid} ${toString s.id} ${lib.escapeShellArg (builtins.toJSON s.values)}\n"
      ) spicesSettings}
    '';

    # Passwordless login keyring, for the autologin user of an unencrypted host
    # only (cf. the header): gnome-keyring tries an empty password before
    # prompting, and stores such a keyring as plain ini, not an encrypted blob.
    home.activation.umiLoginKeyring = lib.mkIf (isAutoLoginUser && !hostHasLuks) (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        keyringDir="$HOME/.local/share/keyrings"
        run ${pkgs.coreutils}/bin/mkdir -p -m 700 "$keyringDir"

        # A keyring that opens without a password starts with `[keyring]`;
        # anything else is the encrypted binary format, locked behind a
        # passphrase nobody can type here. Dropping it is the only way out of
        # the prompt loop. `user.keystore` (PKCS#11 objects) is sealed with the
        # same password and would prompt on its own, so it goes too.
        if [ -e "$keyringDir/login.keyring" ] &&
           [ "$(${pkgs.coreutils}/bin/head -c 9 "$keyringDir/login.keyring")" != "[keyring]" ] ; then
          run ${pkgs.coreutils}/bin/rm -f "$keyringDir/login.keyring" "$keyringDir/user.keystore"
        fi

        if [ ! -e "$keyringDir/login.keyring" ] ; then
          run ${pkgs.coreutils}/bin/install -m 600 ${plainLoginKeyring} "$keyringDir/login.keyring"
        fi

        # Without it, storing a secret in a home that never had a default
        # collection pops the "create a keyring" prompt (cf. home/modules/office.nix).
        if [ ! -e "$keyringDir/default" ] ; then
          run ${pkgs.coreutils}/bin/install -m 600 ${defaultKeyringName} "$keyringDir/default"
        fi
      ''
    );
  };
}
