# This file is generated by 'just generate' or 'just clean'
# from the configuration file etc/config.yaml
# --> DO NOT EDIT <--

{ lib, ... }:
{
  disko.devices.disk.main.device = lib.mkForce "/dev/vda";
}
