# Supervision module with prometheus, grafana and node exporter.
#
# :::tip
# This module is preconfigured with a configuration that allows you
# to monitor the operating system, network activity, resources, and performance.
# For each zone:
#
# - All nodes with tag "monitoring-node" contains prometheus + node exporter.
# - The node with service "monitoring" contains grafana.
# - Only one monitoring host per zone is accepted.
# - A tag "monitoring-node:[zone]" is attached to a monitoring host of the designed zone.
# :::

{
  lib,
  config,
  dnfLib,
  hosts,
  host,
  network,
  zone,
  pkgs,
  ...
}:
let
  cfg = config.darkone.service.monitoring;
  port = {
    grafana = 3222;
    nodeExporter = 9100;
    prometheus = config.services.prometheus.port;
  };

  # Nodes supervised by the current zone
  nodes = lib.filter (
    h: lib.hasAttr "monitoring-node" h.features && h.features.monitoring-node == zone.name
  ) hosts;

  # Service params
  defaultParams = {
    description = "System and Network Statistics";
    icon = "grafana";
  };
  params = dnfLib.extractServiceParams host network "monitoring" defaultParams;

  # OIDC (Kanidm) — auto-provisioned via the template
  # `darkone.service.idm.oauth2.monitoring`. Secret generated by kanidm as
  # `oidc-secret-monitoring` then re-aliased for Grafana (see mkIf cfg.enable).
  inherit
    (dnfLib.mkOidcContext {
      name = "monitoring";
      inherit params network hosts;
    })
    clientId
    secret
    idmUrl
    ;
  oidc = dnfLib.mkKanidmEndpoints idmUrl clientId;
in
{
  options = {
    darkone.service.monitoring.enable = lib.mkEnableOption "Enable monitoring with prometheus, grafana and node exporter";
    darkone.service.monitoring.isNode = lib.mkOption {
      type = lib.types.bool;
      default = lib.hasAttrByPath [ "features" "monitoring-node" ] host;
      description = "Is a monitoring node";
    };
    darkone.service.monitoring.retentionTime = lib.mkOption {
      type = lib.types.str;
      default = "30d";
      description = "Prometheus metrics retention duration";
    };
    darkone.service.monitoring.kioskTarget = lib.mkOption {
      type = lib.types.str;
      default = "d/rYdddlPWk/node-exporter-full?kiosk";
      example = "d/dnf-monitoring-home/home?kiosk";
      description = ''
        Target (relative, no `/`) for the automatic redirect to Grafana
        from the monitoring domain root. Overridden by the Loki module
        when active to point to a multi-source home dashboard.
      '';
    };
  };

  # Prometheus + Grafana + Node Exporter
  config = lib.mkMerge [

    #------------------------------------------------------------------------
    # DNF Service configuration
    #------------------------------------------------------------------------

    {
      darkone.system.services.service.monitoring = {
        inherit defaultParams;
        persist = {
          dbFiles = lib.optional cfg.enable "/var/lib/grafana/grafana.db";
          varDirs = [
            "/var/lib/prometheus2"
          ]
          ++ lib.optionals cfg.enable [
            "/var/lib/grafana/plugins"
            "/var/lib/grafana/data"
          ];
        };
        proxy.enable = cfg.enable;
        proxy.servicePort = lib.mkIf cfg.enable port.grafana;

        # Auth handled natively by Grafana via OIDC (see settings."auth.generic_oauth").
        proxy.isProtected = false;
        proxy.isInternal = true;
        proxy.extraConfig = lib.optionalString cfg.enable "redir / /${cfg.kioskTarget}";
      };

      # Kanidm OAuth2 client template
      darkone.service.idm.oauth2.monitoring = {
        displayName = "Monitoring";
        imageFile = ./../../assets/app-icons/grafana.svg;
        redirectPaths = [ "/login/generic_oauth" ];
        landingPath = "/";
      };
    }

    (lib.mkIf (cfg.enable || cfg.isNode) {

      #--------------------------------------------------------------------------
      # Home page + virtualhost
      #--------------------------------------------------------------------------

      # Darkone service: enable
      darkone.system.services = dnfLib.enableBlock "monitoring";

      #--------------------------------------------------------------------------
      # Sops
      #--------------------------------------------------------------------------

      # Grafana secrets (internal key) + alias for kanidm-owned OIDC secret.
      # The SOPS admin only adds `oidc-secret-monitoring` (encrypted for
      # kanidm via the idm.nix pattern). This alias makes it readable by grafana.
      #
      # `optionalAttrs cfg.enable` (not `mkIf` on the value) because the key
      # `"${secret}-service"` depends on `params` via `clientId`; and `params`
      # is only resolvable on the host that runs the monitoring service. On a
      # plain monitoring-node, `optionalAttrs` short-circuits the key construction.
      sops.secrets = lib.optionalAttrs cfg.enable {
        grafana-secret-key = {
          mode = "0400";
          owner = "grafana";
        };
        "${secret}-service" = {
          mode = "0400";
          owner = "grafana";
          key = secret;
        };
      };

      #--------------------------------------------------------------------------
      # Node exporter
      #--------------------------------------------------------------------------

      # https://github.com/prometheus/node_exporter
      services.prometheus.exporters.node = lib.mkIf cfg.isNode {
        enable = true;
        port = port.nodeExporter;
        openFirewall = false;
        listenAddress = dnfLib.preferredIp host;
        enabledCollectors = [
          "ethtool"
          "interrupts"
          "ksmd"
          "logind"
          "netstat"
          "softirqs"
          "systemd"
          "tcpstat"
          "wifi"
        ];
        disabledCollectors = [
          "bonding"
          "edac"
          "entropy"
          "infiniband"
          "ipvs"
          "powersupplyclass"
          "rapl"
          "schedstat"
          "selinux"
          "xfs"
          "zfs"
        ];
      };

      # Open the node explorer port if needed
      networking.firewall = lib.mkIf cfg.isNode (
        dnfLib.mkInternalFirewall host zone [ port.nodeExporter ]
      );

      # Additional packages
      environment.systemPackages = lib.optionals cfg.isNode [
        pkgs.ethtool
        pkgs.unixtools.netstat
      ];

      # Need network to bind the address
      systemd.services.prometheus-node-exporter = {
        after = [ "network-online.target" ];
        wants = [ "network-online.target" ];
      };

      #--------------------------------------------------------------------------
      # Prometheus
      #--------------------------------------------------------------------------

      # Prometheus (scraping du node exporter)
      services.prometheus = {
        inherit (cfg) enable;
        inherit (cfg) retentionTime;
        scrapeConfigs = lib.optional cfg.enable {
          job_name = "node";
          static_configs = [
            { targets = map (h: "${dnfLib.preferredIp h}:${toString port.nodeExporter}") nodes; }
          ];
          scrape_interval = "15s";
        };
        globalConfig = lib.mkIf cfg.enable {
          scrape_interval = "15s";
          evaluation_interval = "15s";
        };
      };

      #--------------------------------------------------------------------------
      # Grafana
      #--------------------------------------------------------------------------

      # Grafana with datasource + dashboard
      services.grafana = lib.mkIf cfg.enable {
        enable = true;

        settings = {
          server = {
            http_addr = params.ip;
            http_port = port.grafana;
            domain = params.fqdn;
            root_url = params.href;
            serve_from_sub_path = false;
          };

          # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#secret_key
          # After update, re-encryption is needed:
          # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-database-encryption/#re-encrypt-secrets
          security.secret_key = "$__file{${config.sops.secrets.grafana-secret-key.path}}";

          #security = {
          #  admin_user = "admin";
          #  admin_password = "admin";
          #};

          database = {
            type = "sqlite3";
            path = "/var/lib/grafana/grafana.db";
          };
          analytics = {
            reporting_enabled = false;
            check_for_updates = false;
            feedback_links_enabled = false;
            check_for_plugin_updates = false;
          };
          plugins = {
            allow_loading_unsigned_plugins = false;
            plugin_catalog_url = null;
          };
          news = {
            news_feed_enabled = false;
          };

          # SSO Kanidm (OIDC). Any authenticated Kanidm user gets Viewer
          # access; if the `groups` claim contains `admins` (short name or
          # SPN), they are promoted to GrafanaAdmin. Strict restriction to
          # the admins group (`allowed_groups`) is disabled until we confirm
          # the exact claim format on the Kanidm side — see the TODO below,
          # possibly via `darkone.service.idm.oauth2.monitoring.extra`
          # (custom claimMaps / scopeMaps).
          auth.disable_login_form = true;
          "auth.anonymous".enabled = false;
          "auth.generic_oauth" = {
            enabled = true;
            name = "Kanidm";
            client_id = clientId;
            client_secret = "$__file{${config.sops.secrets."${secret}-service".path}}";
            scopes = "openid email profile groups";
            auth_url = oidc.authUrl;
            token_url = oidc.tokenUrl;
            api_url = oidc.userinfoUrl;
            role_attribute_path = "(contains(groups[*], 'admins') || contains(groups[*], 'admins@${network.domain}')) && 'GrafanaAdmin' || 'Viewer'";
            allow_sign_up = true;
            use_pkce = true;
            auto_login = true;
          };
        };

        provision = {
          enable = true;
          datasources.settings.datasources = [
            {
              name = "Prometheus";
              type = "prometheus";
              url = "http://${config.services.prometheus.listenAddress}:${toString config.services.prometheus.port}";
              isDefault = true;
              editable = false;
            }
          ];
          dashboards.settings.providers = [
            {
              name = "Monitoring local";
              disableDeletion = true;
              allowUiUpdates = false;
              options = {
                path = "/etc/grafana-dashboards";
                foldersFromFilesStructure = true;
              };
            }
          ];
        };
      };

      #--------------------------------------------------------------------------
      # Dashboards
      #--------------------------------------------------------------------------

      environment.etc = lib.mkIf cfg.enable {
        "grafana-dashboards/node-explorer.json".source = ./monitoring/node-explorer.json;
      };

      # Open ports in the firewall (commented out — direct access not needed)
      #networking.firewall.allowedTCPPorts = [
      #  port.grafana
      #  port.nodeExporter
      #  port.prometheus
      #];
    })
  ];
}
