# Supervision module with prometheus, grafana and node exporter.
#
# :::tip
# This module is preconfigured with a configuration that allows you
# to monitor the operating system, network activity, resources, and performance.
# For each zone:
#
# - All nodes with tag "monitoring-node" contains prometheus + node exporter.
# - The node with service "monitoring" contains grafana.
# - Only one monitoring host per zone is accepted.
# - A tag "monitoring-node:[zone]" is attached to a monitoring host of the designed zone.
# :::

{
  lib,
  config,
  dnfLib,
  dnfConfig,
  hosts,
  host,
  network,
  zone,
  pkgs,
  ...
}:
let
  cfg = config.darkone.service.monitoring;
  alerting = cfg.alerting;

  # Matrix alerting config declared once in config.yaml (network.matrix), so the
  # bot user and room IDs (provisioned by `just configure-alert-bot`) default
  # from the network and need no per-host repetition.
  mtx = network.matrix or { };
  port = {
    grafana = dnfConfig.network.ports.grafana;
    nodeExporter = dnfConfig.network.ports.nodeExporter;
    prometheus = config.services.prometheus.port;
    alertmanager = dnfConfig.network.ports.alertmanager;
    matrixReceiver = dnfConfig.network.ports.matrixAlertReceiver;
    blackbox = dnfConfig.network.ports.blackboxExporter;
  };

  # Nodes supervised by the current zone
  nodes = lib.filter (
    h: lib.hasAttr "monitoring-node" h.features && h.features.monitoring-node == zone.name
  ) hosts;

  # Service params
  defaultParams = {
    description = "System and Network Statistics";
    icon = "grafana";
  };
  params = dnfLib.extractServiceParams host network "monitoring" defaultParams;

  # OIDC (Kanidm) — auto-provisioned via the template
  # `darkone.service.idm.oauth2.monitoring`. Secret generated by kanidm as
  # `oidc-secret-monitoring` then re-aliased for Grafana (see mkIf cfg.enable).
  inherit
    (dnfLib.mkOidcContext {
      name = "monitoring";
      inherit params network hosts;
    })
    clientId
    secret
    idmUrl
    ;
  oidc = dnfLib.mkKanidmEndpoints idmUrl clientId;

  # Rebuild silence: a monitored node drops `dnf_maintenance 1` into the
  # node_exporter textfile collector dir while applying its config; Prometheus
  # picks it up and Alertmanager inhibits that node's alerts. Purely local.
  textfileDir = "/var/lib/node-exporter-textfile";
  maintenanceScript = pkgs.writeShellApplication {
    name = "dnf-maintenance";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      flag="${textfileDir}/maintenance.prom"
      case "''${1:-}" in
        on)
          # Atomic write so node_exporter never reads a half-written file.
          tmp="$(mktemp "${textfileDir}/.maintenance.XXXXXX")"
          printf 'dnf_maintenance 1\n' > "$tmp"
          mv -f "$tmp" "$flag"
          ;;
        off)
          rm -f "$flag"
          ;;
        *)
          echo "usage: dnf-maintenance on|off" >&2
          exit 1
          ;;
      esac
    '';
  };
in
{
  options = {
    darkone.service.monitoring.enable = lib.mkEnableOption "Enable monitoring with prometheus, grafana and node exporter";
    darkone.service.monitoring.isNode = lib.mkOption {
      type = lib.types.bool;
      default = lib.hasAttrByPath [ "features" "monitoring-node" ] host;
      description = "Is a monitoring node";
    };
    darkone.service.monitoring.retentionTime = lib.mkOption {
      type = lib.types.str;
      default = "30d";
      description = "Prometheus metrics retention duration";
    };
    darkone.service.monitoring.kioskTarget = lib.mkOption {
      type = lib.types.str;
      default = "d/rYdddlPWk/node-exporter-full?kiosk";
      example = "d/dnf-monitoring-home/home?kiosk";
      description = ''
        Target (relative, no `/`) for the automatic redirect to Grafana
        from the monitoring domain root. Overridden by the Loki module
        when active to point to a multi-source home dashboard.
      '';
    };

    # Alerting (Alertmanager + Matrix/email escalation). Lives on the zone
    # monitoring host (alongside Prometheus/Grafana). Severity drives the
    # escalation: warning -> Matrix #warnings, critical -> Matrix #incidents +
    # mail. Node class (critical/non-critical/disabled) comes from the `alert-*`
    # features or the host profile (see dnfLib alerts helpers).
    darkone.service.monitoring.alerting = {
      enable = lib.mkEnableOption "Alertmanager-based alerting on the zone monitoring host";

      matrix = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Deliver alerts to Matrix rooms via the matrix-alertmanager bot";
        };
        userId = lib.mkOption {
          type = lib.types.str;
          default = if (mtx.bot or "") != "" then "@${mtx.bot}:${network.domain}" else "";
          example = "@alertbot:poncon.fr";
          description = "Matrix user ID of the alert bot (defaults from network.matrix.bot)";
        };
        warningsRoom = lib.mkOption {
          type = lib.types.str;
          default = mtx.warningsRoom or "";
          example = "!warnings:poncon.fr";
          description = "Matrix room ID for warnings (defaults from network.matrix.warningsRoom)";
        };
        incidentsRoom = lib.mkOption {
          type = lib.types.str;
          default = mtx.incidentsRoom or "";
          example = "!incidents:poncon.fr";
          description = "Matrix room ID for incidents (defaults from network.matrix.incidentsRoom)";
        };
      };

      email = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Also send critical alerts by mail (through the local Postfix relay)";
        };
        to = lib.mkOption {
          type = lib.types.str;
          default = "admin@${network.domain}";
          description = "Recipient of critical alert mails";
        };
      };

      network.enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Probe network reachability (gateway/tailnet/DNS) with blackbox_exporter";
      };

      silenceOnRebuild = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Ship the dnf-maintenance flag (textfile collector) so rebuilds inhibit a node's alerts";
      };

      thresholds = lib.mkOption {
        type = lib.types.attrs;
        default = { };
        example = {
          diskFreePercentWarn = 10;
        };
        description = "Override resource alert thresholds (see dnf/lib/alerts.nix defaults)";
      };
    };
  };

  # Prometheus + Grafana + Node Exporter
  config = lib.mkMerge [

    #------------------------------------------------------------------------
    # DNF Service configuration
    #------------------------------------------------------------------------

    {
      darkone.system.services.service.monitoring = {
        inherit defaultParams;
        persist = {
          dbFiles = lib.optional cfg.enable "/var/lib/grafana/grafana.db";
          varDirs = [
            "/var/lib/prometheus2"
          ]
          ++ lib.optionals cfg.enable [
            "/var/lib/grafana/plugins"
            "/var/lib/grafana/data"
          ];
        };
        proxy.enable = cfg.enable;
        proxy.servicePort = lib.mkIf cfg.enable port.grafana;

        # Auth handled natively by Grafana via OIDC (see settings."auth.generic_oauth").
        proxy.isProtected = false;
        proxy.isInternal = true;
        proxy.extraConfig = lib.optionalString cfg.enable "redir / /${cfg.kioskTarget}";
      };

      # Kanidm OAuth2 client template
      darkone.service.idm.oauth2.monitoring = {
        displayName = "Monitoring";
        imageFile = ./../../assets/app-icons/grafana.svg;
        redirectPaths = [ "/login/generic_oauth" ];
        landingPath = "/";
      };
    }

    (lib.mkIf (cfg.enable || cfg.isNode) {

      #--------------------------------------------------------------------------
      # Home page + virtualhost
      #--------------------------------------------------------------------------

      # Darkone service: enable
      darkone.system.services = dnfLib.enableBlock "monitoring";

      #--------------------------------------------------------------------------
      # Sops
      #--------------------------------------------------------------------------

      # Grafana secrets (internal key) + alias for kanidm-owned OIDC secret.
      # The SOPS admin only adds `oidc-secret-monitoring` (encrypted for
      # kanidm via the idm.nix pattern). This alias makes it readable by grafana.
      #
      # `optionalAttrs cfg.enable` (not `mkIf` on the value) because the key
      # `"${secret}-service"` depends on `params` via `clientId`; and `params`
      # is only resolvable on the host that runs the monitoring service. On a
      # plain monitoring-node, `optionalAttrs` short-circuits the key construction.
      sops.secrets = lib.optionalAttrs cfg.enable {
        grafana-secret-key = {
          mode = "0400";
          owner = "grafana";
        };
        "${secret}-service" = {
          mode = "0400";
          owner = "grafana";
          key = secret;
        };
      };

      #--------------------------------------------------------------------------
      # Node exporter
      #--------------------------------------------------------------------------

      # https://github.com/prometheus/node_exporter
      services.prometheus.exporters.node = lib.mkIf cfg.isNode {
        enable = true;
        port = port.nodeExporter;
        openFirewall = false;
        listenAddress = dnfLib.preferredIp host;
        enabledCollectors = [
          "ethtool"
          "interrupts"
          "ksmd"
          "logind"
          "netstat"
          "softirqs"
          "systemd"
          "tcpstat"
          "wifi"
        ];
        disabledCollectors = [
          "bonding"
          "edac"
          "entropy"
          "infiniband"
          "ipvs"
          "powersupplyclass"
          "rapl"
          "schedstat"
          "selinux"
          "xfs"
          "zfs"
        ];
      };

      # Open the node explorer port if needed
      networking.firewall = lib.mkIf cfg.isNode (
        dnfLib.mkInternalFirewall host zone [ port.nodeExporter ]
      );

      # Additional packages
      environment.systemPackages = lib.optionals cfg.isNode [
        pkgs.ethtool
        pkgs.unixtools.netstat
      ];

      # Need network to bind the address
      systemd.services.prometheus-node-exporter = {
        after = [ "network-online.target" ];
        wants = [ "network-online.target" ];
      };

      #--------------------------------------------------------------------------
      # Prometheus
      #--------------------------------------------------------------------------

      # Prometheus (scraping du node exporter)
      services.prometheus = {
        inherit (cfg) enable;
        inherit (cfg) retentionTime;
        scrapeConfigs = lib.optional cfg.enable {
          job_name = "node";
          static_configs = [
            { targets = map (h: "${dnfLib.preferredIp h}:${toString port.nodeExporter}") nodes; }
          ];
          scrape_interval = "15s";
        };
        globalConfig = lib.mkIf cfg.enable {
          scrape_interval = "15s";
          evaluation_interval = "15s";
        };
      };

      #--------------------------------------------------------------------------
      # Grafana
      #--------------------------------------------------------------------------

      # Grafana with datasource + dashboard
      services.grafana = lib.mkIf cfg.enable {
        enable = true;

        settings = {
          server = {
            http_addr = params.ip;
            http_port = port.grafana;
            domain = params.fqdn;
            root_url = params.href;
            serve_from_sub_path = false;
          };

          # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#secret_key
          # After update, re-encryption is needed:
          # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-database-encryption/#re-encrypt-secrets
          security.secret_key = "$__file{${config.sops.secrets.grafana-secret-key.path}}";

          #security = {
          #  admin_user = "admin";
          #  admin_password = "admin";
          #};

          database = {
            type = "sqlite3";
            path = "/var/lib/grafana/grafana.db";
          };
          analytics = {
            reporting_enabled = false;
            check_for_updates = false;
            feedback_links_enabled = false;
            check_for_plugin_updates = false;
          };
          plugins = {
            allow_loading_unsigned_plugins = false;
            plugin_catalog_url = null;
          };
          news = {
            news_feed_enabled = false;
          };

          # SSO Kanidm (OIDC). Any authenticated Kanidm user gets Viewer
          # access; if the `groups` claim contains `admins` (short name or
          # SPN), they are promoted to GrafanaAdmin. Strict restriction to
          # the admins group (`allowed_groups`) is disabled until we confirm
          # the exact claim format on the Kanidm side — see the TODO below,
          # possibly via `darkone.service.idm.oauth2.monitoring.extra`
          # (custom claimMaps / scopeMaps).
          auth.disable_login_form = true;
          "auth.anonymous".enabled = false;
          "auth.generic_oauth" = {
            enabled = true;
            name = "Kanidm";
            client_id = clientId;
            client_secret = "$__file{${config.sops.secrets."${secret}-service".path}}";
            scopes = "openid email profile groups";
            auth_url = oidc.authUrl;
            token_url = oidc.tokenUrl;
            api_url = oidc.userinfoUrl;
            role_attribute_path = "(contains(groups[*], 'admins') || contains(groups[*], 'admins@${network.domain}')) && 'GrafanaAdmin' || 'Viewer'";
            allow_sign_up = true;
            use_pkce = true;
            auto_login = true;
          };
        };

        provision = {
          enable = true;
          datasources.settings.datasources = [
            {
              name = "Prometheus";
              type = "prometheus";
              url = "http://${config.services.prometheus.listenAddress}:${toString config.services.prometheus.port}";
              isDefault = true;
              editable = false;
            }
          ];
          dashboards.settings.providers = [
            {
              name = "Monitoring local";
              disableDeletion = true;
              allowUiUpdates = false;
              options = {
                path = "/etc/grafana-dashboards";
                foldersFromFilesStructure = true;
              };
            }
          ];
        };
      };

      #--------------------------------------------------------------------------
      # Dashboards
      #--------------------------------------------------------------------------

      environment.etc = lib.mkIf cfg.enable {
        "grafana-dashboards/node-explorer.json".source = ./monitoring/node-explorer.json;
      };

      # Open ports in the firewall (commented out — direct access not needed)
      #networking.firewall.allowedTCPPorts = [
      #  port.grafana
      #  port.nodeExporter
      #  port.prometheus
      #];
    })

    #--------------------------------------------------------------------------
    # Alerting — Alertmanager + Matrix/email escalation (severity-based)
    #--------------------------------------------------------------------------

    (lib.mkIf (cfg.enable && alerting.enable) {

      assertions = [
        {
          assertion =
            !alerting.matrix.enable
            || (
              alerting.matrix.userId != ""
              && alerting.matrix.warningsRoom != ""
              && alerting.matrix.incidentsRoom != ""
            );
          message = "darkone.service.monitoring.alerting.matrix: userId, warningsRoom and incidentsRoom are required when Matrix delivery is enabled.";
        }
      ];

      # Critical alerts escalate to mail through the framework's local relay, so
      # it must run here: Postfix owns the 465/SASL/TLS handshake, Alertmanager
      # only talks plain SMTP to localhost.
      darkone.service.postfix.enable = lib.mkIf alerting.email.enable (lib.mkDefault true);

      # Bot access token + shared webhook secret. The same webhook secret is fed
      # to Alertmanager via env so the receiver URL it builds matches the bot.
      sops.secrets = lib.mkIf alerting.matrix.enable {
        alertmanager-matrix-token = { };
        alertmanager-webhook-secret = { };
      };
      sops.templates = lib.mkIf alerting.matrix.enable {
        alertmanager-env.content = ''
          WEBHOOK_SECRET=${config.sops.placeholder.alertmanager-webhook-secret}
        '';
      };

      # Matrix delivery bot: maps an Alertmanager receiver name to a room.
      services.matrix-alertmanager = lib.mkIf alerting.matrix.enable {
        enable = true;
        port = port.matrixReceiver;
        homeserverUrl = "https://matrix.${network.domain}";
        matrixUser = alerting.matrix.userId;
        tokenFile = config.sops.secrets.alertmanager-matrix-token.path;
        secretFile = config.sops.secrets.alertmanager-webhook-secret.path;
        matrixRooms = [
          {
            receivers = [ "matrix-warnings" ];
            roomId = alerting.matrix.warningsRoom;
          }
          {
            receivers = [ "matrix-incidents" ];
            roomId = alerting.matrix.incidentsRoom;
          }
        ];
      };

      # Alertmanager: dedup + grouping + severity routing + inhibition.
      services.prometheus.alertmanager = {
        enable = true;
        port = port.alertmanager;
        listenAddress = "127.0.0.1";
        environmentFile = lib.mkIf alerting.matrix.enable config.sops.templates.alertmanager-env.path;

        # `$WEBHOOK_SECRET` is substituted at runtime from environmentFile; the
        # build-time amtool check sees the literal, so it is disabled.
        checkConfig = false;

        configuration = {
          route = {
            group_by = [
              "alertname"
              "instance"
            ];
            group_wait = "30s";
            group_interval = "5m";
            repeat_interval = "4h";
            receiver = "matrix-warnings";
            routes =
              # Maintenance alerts are swallowed: they exist only to drive
              # inhibition, never to notify.
              lib.optional alerting.silenceOnRebuild {
                matchers = [ ''alertname="MaintenanceMode"'' ];
                receiver = "null";
              }
              ++ [
                {
                  matchers = [ ''severity="critical"'' ];
                  receiver = "matrix-incidents";
                }
                {
                  matchers = [ ''severity="warning"'' ];
                  receiver = "matrix-warnings";
                }
              ];
          };

          inhibit_rules =
            # A firing critical mutes the matching warning for the same target.
            [
              {
                source_matchers = [ ''severity="critical"'' ];
                target_matchers = [ ''severity="warning"'' ];
                equal = [
                  "alertname"
                  "instance"
                ];
              }
            ]
            # A node under maintenance mutes all of its own alerts.
            ++ lib.optional alerting.silenceOnRebuild {
              source_matchers = [ ''alertname="MaintenanceMode"'' ];
              target_matchers = [ ''severity=~".+"'' ];
              equal = [ "instance" ];
            };

          receivers = lib.optional alerting.silenceOnRebuild { name = "null"; } ++ [
            {
              name = "matrix-warnings";
              webhook_configs = lib.optionals alerting.matrix.enable [
                {
                  url = "http://127.0.0.1:${toString port.matrixReceiver}/alerts?secret=$WEBHOOK_SECRET";
                  send_resolved = true;
                }
              ];
            }
            {
              name = "matrix-incidents";
              webhook_configs = lib.optionals alerting.matrix.enable [
                {
                  url = "http://127.0.0.1:${toString port.matrixReceiver}/alerts?secret=$WEBHOOK_SECRET";
                  send_resolved = true;
                }
              ];
              email_configs = lib.optionals alerting.email.enable [
                {
                  to = alerting.email.to;
                  from = "alertmanager@${network.domain}";
                  smarthost = "localhost:25";
                  require_tls = false;
                  send_resolved = true;
                }
              ];
            }
          ];
        };
      };

      # Point Prometheus at the local Alertmanager and load the generated rules.
      services.prometheus.alertmanagers = [
        { static_configs = [ { targets = [ "127.0.0.1:${toString port.alertmanager}" ]; } ]; }
      ];
      services.prometheus.rules = [
        (builtins.toJSON (
          dnfLib.mkAlertRuleGroups {
            inherit nodes;
            services = network.services;
            nodeExporterPort = port.nodeExporter;
            zoneName = zone.name;
            inherit (alerting) thresholds;
          }
        ))
      ]
      ++ lib.optional alerting.silenceOnRebuild (
        builtins.toJSON (dnfLib.mkMaintenanceRuleGroups { zoneName = zone.name; })
      );
    })

    #--------------------------------------------------------------------------
    # Network reachability — blackbox probes (gateway / tailnet / DNS)
    #--------------------------------------------------------------------------

    (lib.mkIf (cfg.enable && alerting.enable && alerting.network.enable) (
      let

        # Zone gateway (DNS/DHCP/router) and the headscale coordination server:
        # the two single points whose loss breaks the zone or the tailnet.
        gwIp = zone.gateway.vpn.ipv4 or "";
        hcsHost = dnfLib.findHost network.coordination.hostname dnfLib.constants.globalZone hosts;
        hcsIp = hcsHost.vpnIp or "";

        # A name that must always resolve through the zone resolver; failure to
        # answer it flags a DNS problem.
        controlName = "idm.${network.domain}";
        dnsTarget = "${gwIp}:53";

        icmpTargets = lib.filter (x: x != "") [
          gwIp
          hcsIp
        ];

        # Blackbox prober definitions (ICMP reachability + DNS resolution).
        blackboxConfig = (pkgs.formats.yaml { }).generate "blackbox.yml" {
          modules = {
            icmp = {
              prober = "icmp";
              timeout = "5s";
              icmp.preferred_ip_protocol = "ip4";
            };
            dns = {
              prober = "dns";
              timeout = "5s";
              dns = {
                query_name = controlName;
                query_type = "A";
                preferred_ip_protocol = "ip4";
              };
            };
          };
        };

        # Standard blackbox scrape: the probed address travels as `instance`,
        # the request itself is sent to the local exporter.
        mkBlackboxJob = jobName: moduleName: targets: {
          job_name = jobName;
          metrics_path = "/probe";
          params.module = [ moduleName ];
          static_configs = [ { inherit targets; } ];
          scrape_interval = "30s";
          relabel_configs = [
            {
              source_labels = [ "__address__" ];
              target_label = "__param_target";
            }
            {
              source_labels = [ "__param_target" ];
              target_label = "instance";
            }
            {
              target_label = "__address__";
              replacement = "127.0.0.1:${toString port.blackbox}";
            }
          ];
        };

        # One alert per probe target, named and severity-tagged: gateway/tailnet
        # losses page, a DNS miss warns.
        probes =
          (lib.optional (gwIp != "") {
            name = "gateway ${zone.name} (${gwIp})";
            instance = gwIp;
            job = "blackbox-icmp";
            severity = "critical";
          })
          ++ (lib.optional (hcsIp != "") {
            name = "tailnet coordination ${network.coordination.hostname} (${hcsIp})";
            instance = hcsIp;
            job = "blackbox-icmp";
            severity = "critical";
          })
          ++ (lib.optional (gwIp != "") {
            name = "DNS resolver ${gwIp}";
            instance = dnsTarget;
            job = "blackbox-dns";
            severity = "warning";
            "for" = "5m";
          });
      in
      {
        services.prometheus.exporters.blackbox = {
          enable = true;
          port = port.blackbox;
          listenAddress = "127.0.0.1";
          openFirewall = false;
          configFile = blackboxConfig;
        };

        services.prometheus.scrapeConfigs =
          (lib.optional (icmpTargets != [ ]) (mkBlackboxJob "blackbox-icmp" "icmp" icmpTargets))
          ++ (lib.optional (gwIp != "") (mkBlackboxJob "blackbox-dns" "dns" [ dnsTarget ]));

        services.prometheus.rules = [
          (builtins.toJSON (
            dnfLib.mkNetworkRuleGroups {
              zoneName = zone.name;
              inherit probes;
            }
          ))
        ];
      }
    ))

    #--------------------------------------------------------------------------
    # Rebuild silence — per-node maintenance flag (textfile collector)
    #--------------------------------------------------------------------------

    (lib.mkIf (cfg.isNode && alerting.silenceOnRebuild) {

      # Expose the textfile collector dir and ship the `dnf-maintenance on|off`
      # helper the deploy flow wraps around nixos-rebuild test/switch.
      services.prometheus.exporters.node.extraFlags = [ "--collector.textfile.directory=${textfileDir}" ];
      systemd.tmpfiles.rules = [ "d ${textfileDir} 0755 root root -" ];
      environment.systemPackages = [ maintenanceScript ];
    })
  ];
}
