# Supervision module: Grafana dashboards + per-node exporter.
#
# :::tip
# Grafana visualises the metrics collected by the `prometheus` service (which it
# requires on the same host, enforced by the generator). For each zone:
#
# - All nodes with tag "monitoring-node" run the node exporter.
# - The node with service "monitoring" runs Grafana (and requires `prometheus`).
# - Only one monitoring host per zone is accepted.
# - A tag "monitoring-node:[zone]" attaches a node to that zone's Prometheus.
# :::

{
  lib,
  config,
  dnfLib,
  dnfConfig,
  hosts,
  host,
  network,
  zone,
  pkgs,
  ...
}:
let
  cfg = config.darkone.service.monitoring;

  # Rebuild silence is owned by the prometheus alerting block; the per-node flag
  # writer below only needs to know whether to ship the maintenance helper.
  silenceOnRebuild = config.darkone.service.prometheus.alerting.silenceOnRebuild;

  port = {
    grafana = dnfConfig.network.ports.grafana;
    nodeExporter = dnfConfig.network.ports.nodeExporter;
    smartctlExporter = dnfConfig.network.ports.smartctlExporter;
  };

  # Service params
  defaultParams = {
    description = "System and Network Statistics";
    icon = "grafana";
  };
  params = dnfLib.extractServiceParams host network "monitoring" defaultParams;

  # OIDC (Kanidm) — auto-provisioned via the template
  # `darkone.service.idm.oauth2.monitoring`. Secret generated by kanidm as
  # `oidc-secret-monitoring` then re-aliased for Grafana (see mkIf cfg.enable).
  inherit
    (dnfLib.mkOidcContext {
      name = "monitoring";
      inherit params network hosts;
    })
    clientId
    secret
    idmUrl
    ;
  oidc = dnfLib.mkKanidmEndpoints idmUrl clientId;

  # Rebuild silence: a monitored node drops `dnf_maintenance 1` into the
  # node_exporter textfile collector dir while applying its config; Prometheus
  # picks it up and Alertmanager inhibits that node's alerts. Purely local.
  textfileDir = "/var/lib/node-exporter-textfile";
  maintenanceScript = pkgs.writeShellApplication {
    name = "dnf-maintenance";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      flag="${textfileDir}/maintenance.prom"
      case "''${1:-}" in
        on)
          # Atomic write so node_exporter never reads a half-written file.
          tmp="$(mktemp "${textfileDir}/.maintenance.XXXXXX")"
          printf 'dnf_maintenance 1\n' > "$tmp"

          # mktemp creates 0600; node_exporter runs as a non-root user and must
          # read the file, so widen before the atomic rename.
          chmod 0644 "$tmp"
          mv -f "$tmp" "$flag"
          ;;
        off)
          rm -f "$flag"
          ;;
        *)
          echo "usage: dnf-maintenance on|off" >&2
          exit 1
          ;;
      esac
    '';
  };
in
{
  options = {
    darkone.service.monitoring.enable = lib.mkEnableOption "Enable monitoring with prometheus, grafana and node exporter";
    darkone.service.monitoring.isNode = lib.mkOption {
      type = lib.types.bool;
      default = lib.hasAttrByPath [ "features" "monitoring-node" ] host;
      description = "Is a monitoring node";
    };
    darkone.service.monitoring.kioskTarget = lib.mkOption {
      type = lib.types.str;
      default = "d/rYdddlPWk/node-exporter-full?kiosk";
      example = "d/dnf-monitoring-home/home?kiosk";
      description = ''
        Target (relative, no `/`) for the automatic redirect to Grafana
        from the monitoring domain root. Overridden by the Loki module
        when active to point to a multi-source home dashboard.
      '';
    };
  };

  # Grafana dashboards + per-node exporter (Prometheus lives in prometheus.nix)
  config = lib.mkMerge [

    #------------------------------------------------------------------------
    # DNF Service configuration
    #------------------------------------------------------------------------

    {
      darkone.system.services.service.monitoring = {
        inherit defaultParams;
        persist = {
          dbFiles = lib.optional cfg.enable "/var/lib/grafana/grafana.db";
          varDirs = lib.optionals cfg.enable [
            "/var/lib/grafana/plugins"
            "/var/lib/grafana/data"
          ];
        };
        proxy.enable = cfg.enable;
        proxy.servicePort = lib.mkIf cfg.enable port.grafana;

        # Auth handled natively by Grafana via OIDC (see settings."auth.generic_oauth").
        proxy.isProtected = false;
        proxy.isInternal = true;
        proxy.extraConfig = lib.optionalString cfg.enable "redir / /${cfg.kioskTarget}";
      };

      # Kanidm OAuth2 client template
      darkone.service.idm.oauth2.monitoring = {
        displayName = "Monitoring";
        imageFile = ./../../assets/app-icons/grafana.svg;
        redirectPaths = [ "/login/generic_oauth" ];
        landingPath = "/";
      };
    }

    (lib.mkIf (cfg.enable || cfg.isNode) {

      #--------------------------------------------------------------------------
      # Home page + virtualhost
      #--------------------------------------------------------------------------

      # Darkone service: enable
      darkone.system.services = dnfLib.enableBlock "monitoring";

      #--------------------------------------------------------------------------
      # Sops
      #--------------------------------------------------------------------------

      # Grafana secrets (internal key) + alias for kanidm-owned OIDC secret.
      # The SOPS admin only adds `oidc-secret-monitoring` (encrypted for
      # kanidm via the idm.nix pattern). This alias makes it readable by grafana.
      #
      # `optionalAttrs cfg.enable` (not `mkIf` on the value) because the key
      # `"${secret}-service"` depends on `params` via `clientId`; and `params`
      # is only resolvable on the host that runs the monitoring service. On a
      # plain monitoring-node, `optionalAttrs` short-circuits the key construction.
      sops.secrets = lib.optionalAttrs cfg.enable {
        grafana-secret-key = {
          mode = "0400";
          owner = "grafana";
        };
        "${secret}-service" = {
          mode = "0400";
          owner = "grafana";
          key = secret;
        };
      };

      #--------------------------------------------------------------------------
      # Node exporter
      #--------------------------------------------------------------------------

      # https://github.com/prometheus/node_exporter
      services.prometheus.exporters.node = lib.mkIf cfg.isNode {
        enable = true;
        port = port.nodeExporter;
        openFirewall = false;
        listenAddress = dnfLib.preferredIp host;
        enabledCollectors = [
          "ethtool"
          "interrupts"
          "ksmd"
          "logind"
          "netstat"
          "softirqs"
          "systemd"
          "tcpstat"
          "wifi"
        ];
        disabledCollectors = [
          "bonding"
          "edac"
          "entropy"
          "infiniband"
          "ipvs"
          "powersupplyclass"
          "rapl"
          "schedstat"
          "selinux"
          "xfs"
          "zfs"
        ];
      };

      # https://github.com/prometheus-community/smartctl_exporter
      # Disk SMART health, scraped per node like the node exporter. On a host
      # without SMART-capable disks (e.g. a VPS) it simply exports no device.
      services.prometheus.exporters.smartctl = lib.mkIf cfg.isNode {
        enable = true;
        port = port.smartctlExporter;
        openFirewall = false;
        listenAddress = dnfLib.preferredIp host;
      };

      # Open the node explorer + smartctl ports if needed
      networking.firewall = lib.mkIf cfg.isNode (
        dnfLib.mkInternalFirewall host zone [
          port.nodeExporter
          port.smartctlExporter
        ]
      );

      # Additional packages
      environment.systemPackages = lib.optionals cfg.isNode [
        pkgs.ethtool
        pkgs.unixtools.netstat
      ];

      # Need network to bind the address
      systemd.services.prometheus-node-exporter = {
        after = [ "network-online.target" ];
        wants = [ "network-online.target" ];
      };

      #--------------------------------------------------------------------------
      # Grafana
      #--------------------------------------------------------------------------

      # Grafana with datasource + dashboard
      services.grafana = lib.mkIf cfg.enable {
        enable = true;

        settings = {
          server = {
            http_addr = params.ip;
            http_port = port.grafana;
            domain = params.fqdn;
            root_url = params.href;
            serve_from_sub_path = false;
          };

          # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#secret_key
          # After update, re-encryption is needed:
          # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-database-encryption/#re-encrypt-secrets
          security.secret_key = "$__file{${config.sops.secrets.grafana-secret-key.path}}";

          #security = {
          #  admin_user = "admin";
          #  admin_password = "admin";
          #};

          database = {
            type = "sqlite3";
            path = "/var/lib/grafana/grafana.db";
          };
          analytics = {
            reporting_enabled = false;
            check_for_updates = false;
            feedback_links_enabled = false;
            check_for_plugin_updates = false;
          };
          plugins = {
            allow_loading_unsigned_plugins = false;
            plugin_catalog_url = null;
          };
          news = {
            news_feed_enabled = false;
          };

          # SSO Kanidm (OIDC). Any authenticated Kanidm user gets Viewer
          # access; if the `groups` claim contains `admins` (short name or
          # SPN), they are promoted to GrafanaAdmin. Strict restriction to
          # the admins group (`allowed_groups`) is disabled until we confirm
          # the exact claim format on the Kanidm side — see the TODO below,
          # possibly via `darkone.service.idm.oauth2.monitoring.extra`
          # (custom claimMaps / scopeMaps).
          auth.disable_login_form = true;
          "auth.anonymous".enabled = false;
          "auth.generic_oauth" = {
            enabled = true;
            name = "Kanidm";
            client_id = clientId;
            client_secret = "$__file{${config.sops.secrets."${secret}-service".path}}";
            scopes = "openid email profile groups";
            auth_url = oidc.authUrl;
            token_url = oidc.tokenUrl;
            api_url = oidc.userinfoUrl;
            role_attribute_path = "(contains(groups[*], 'admins') || contains(groups[*], 'admins@${network.domain}')) && 'GrafanaAdmin' || 'Viewer'";
            allow_sign_up = true;
            use_pkce = true;
            auto_login = true;
          };
        };

        provision = {
          enable = true;
          datasources.settings.datasources = [
            {
              name = "Prometheus";
              type = "prometheus";
              url = "http://${config.services.prometheus.listenAddress}:${toString config.services.prometheus.port}";
              isDefault = true;
              editable = false;
            }
          ];
          dashboards.settings.providers = [
            {
              name = "Monitoring local";
              disableDeletion = true;
              allowUiUpdates = false;
              options = {
                path = "/etc/grafana-dashboards";
                foldersFromFilesStructure = true;
              };
            }
          ];
        };
      };

      #--------------------------------------------------------------------------
      # Dashboards
      #--------------------------------------------------------------------------

      environment.etc = lib.mkIf cfg.enable {
        "grafana-dashboards/node-explorer.json".source = ./monitoring/node-explorer.json;
      };

      # Open ports in the firewall (commented out — direct access not needed)
      #networking.firewall.allowedTCPPorts = [
      #  port.grafana
      #  port.nodeExporter
      #  port.prometheus
      #];
    })

    #--------------------------------------------------------------------------
    # Rebuild silence — per-node maintenance flag (textfile collector)
    #--------------------------------------------------------------------------

    (lib.mkIf (cfg.isNode && silenceOnRebuild) {

      # Expose the textfile collector dir and ship the `dnf-maintenance on|off`
      # helper the deploy flow wraps around nixos-rebuild test/switch.
      services.prometheus.exporters.node.extraFlags = [ "--collector.textfile.directory=${textfileDir}" ];
      systemd.tmpfiles.rules = [ "d ${textfileDir} 0755 root root -" ];
      environment.systemPackages = [ maintenanceScript ];
    })
  ];
}
